### ISSUE TITLE
KubernetesApiSpec flaky

### ISSUE THREAD

**Issue by raboof** [apache/pekko-management#216]
```
[info] KubernetesApiSpec:
[info] Kubernetes lease resource
[info] - should be able to be created *** FAILED *** (1 second, 466 milliseconds)
[info]   The future returned an exception of type: org.apache.pekko.coordination.lease.LeaseTimeoutException, with message: Timed out removing lease [lease-1]. It is not known if the remove happened. Is the API server up?. (KubernetesApiSpec.scala:104)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:259)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:281)
[info]   at org.apache.pekko.coordination.lease.kubernetes.KubernetesApiSpec.f$proxy1$1(KubernetesApiSpec.scala:104)
[info]   at org.apache.pekko.coordination.lease.kubernetes.KubernetesApiSpec.$init$$$anonfun$1$$anonfun$1(KubernetesApiSpec.scala:82)
```

... perhaps we could just give it some more time?

**Comment by Roiocam** [comment]
https://github.com/apache/pekko-management/actions/runs/9262642464/job/25479852758

**Comment by raboof** [comment]
despite https://github.com/apache/pekko-management/pull/314 we still saw this again in https://github.com/apache/pekko-management/actions/runs/11159872817/job/31019175982?pr=324 , within 1.5s. I wonder if the timeout is being picked up correctly?

```
should be able to be created *** FAILED *** (1 second, 430 milliseconds)
[info]   The future returned an exception of type: org.apache.pekko.coordination.lease.LeaseTimeoutException, with message: Timed out removing lease [lease-1]. It is not known if the remove happened. Is the API server up?. (KubernetesApiSpec.scala:105)
[info]   org.scalatest.exceptions.TestFailedException:
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:333)
```

**Comment by pjfanning** [comment]
merged #842 - will leave closed for now but will reopen if 842 doesn't help
